//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHR.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_id {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_id() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DHR.Resources.Resource.id", typeof(Resource_id).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentang Saya.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunjangan.
        /// </summary>
        public static string Allowance {
            get {
                return ResourceManager.GetString("Allowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunjangan Perhari.
        /// </summary>
        public static string AllowanceDays {
            get {
                return ResourceManager.GetString("AllowanceDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Tunjangan.
        /// </summary>
        public static string AllowanceTotal {
            get {
                return ResourceManager.GetString("AllowanceTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kehadiran.
        /// </summary>
        public static string AttendanceMenu {
            get {
                return ResourceManager.GetString("AttendanceMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manfaat.
        /// </summary>
        public static string Benefit {
            get {
                return ResourceManager.GetString("Benefit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perjalanan Dinas.
        /// </summary>
        public static string BusinessTravelRequest {
            get {
                return ResourceManager.GetString("BusinessTravelRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hari Kalender.
        /// </summary>
        public static string CalendarDays {
            get {
                return ResourceManager.GetString("CalendarDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubah Kata Sandi Anda.
        /// </summary>
        public static string ChangeyourPassword {
            get {
                return ResourceManager.GetString("ChangeyourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutup.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perusahaan.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfirmasi Kata Sandi.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanggal.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departemen.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubah Kata Sandi.
        /// </summary>
        public static string EditPassword {
            get {
                return ResourceManager.GetString("EditPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tingkat Pendidikan.
        /// </summary>
        public static string EducationLevel {
            get {
                return ResourceManager.GetString("EducationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pegawai.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keluarga.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masuk.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rawat Inap.
        /// </summary>
        public static string InpatientCare {
            get {
                return ResourceManager.GetString("InpatientCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jabatan.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terlambat.
        /// </summary>
        public static string Late {
            get {
                return ResourceManager.GetString("Late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuti.
        /// </summary>
        public static string LeaveRequest {
            get {
                return ResourceManager.GetString("LeaveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cuti.
        /// </summary>
        public static string LeaveTaken {
            get {
                return ResourceManager.GetString("LeaveTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manajemen.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biaya Melahirkan.
        /// </summary>
        public static string MaternityExpenses {
            get {
                return ResourceManager.GetString("MaternityExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klaim Medis.
        /// </summary>
        public static string MedicalClaimMenu {
            get {
                return ResourceManager.GetString("MedicalClaimMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info Lebih Lanjut.
        /// </summary>
        public static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kata Sandi Baru.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perhatian.
        /// </summary>
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kata Sandi Lama.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kacamata.
        /// </summary>
        public static string OpticalServices {
            get {
                return ResourceManager.GetString("OpticalServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keluar.
        /// </summary>
        public static string Out {
            get {
                return ResourceManager.GetString("Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rawat Jalan.
        /// </summary>
        public static string OutpatientCare {
            get {
                return ResourceManager.GetString("OutpatientCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izin.
        /// </summary>
        public static string PermissionRequest {
            get {
                return ResourceManager.GetString("PermissionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permintaan.
        /// </summary>
        public static string RequestMenu {
            get {
                return ResourceManager.GetString("RequestMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simpan.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak Masuk.
        /// </summary>
        public static string TimeOff {
            get {
                return ResourceManager.GetString("TimeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satuan.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jika Anda merasa telah mengajukan perjalanan dinas namun data belum muncul, silakan hubungi HRD..
        /// </summary>
        public static string UserBusinessTripNullAlert {
            get {
                return ResourceManager.GetString("UserBusinessTripNullAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jika Anda merasa telah mengajukan izin masuk kerja namun data belum muncul, silakan hubungi HRD..
        /// </summary>
        public static string UserEntryPermissionNullAlert {
            get {
                return ResourceManager.GetString("UserEntryPermissionNullAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jika Anda merasa telah melakukan klaim rawat inap namun data belum muncul, silakan hubungi HRD..
        /// </summary>
        public static string UserInpatientNullAlert {
            get {
                return ResourceManager.GetString("UserInpatientNullAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jika Anda merasa telah mengajukan cuti namun data belum muncul, silakan hubungi HRD..
        /// </summary>
        public static string UserLeaveNullAlert {
            get {
                return ResourceManager.GetString("UserLeaveNullAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jika Anda merasa telah melakukan klaim biaya kelahiran namun data belum muncul, silakan hubungi HRD..
        /// </summary>
        public static string UserMaternityNullAlert {
            get {
                return ResourceManager.GetString("UserMaternityNullAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jika Anda merasa telah melakukan klaim layanan kacamata namun data belum muncul, silakan hubungi HRD..
        /// </summary>
        public static string UserOpticalNullAlert {
            get {
                return ResourceManager.GetString("UserOpticalNullAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jika Anda merasa telah melakukan klaim rawat jalan namun data belum muncul, silakan hubungi HRD..
        /// </summary>
        public static string UserOutpatientNullAlert {
            get {
                return ResourceManager.GetString("UserOutpatientNullAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jika Anda merasa telah mengajukan izin namun data belum muncul, silakan hubungi HRD..
        /// </summary>
        public static string UserPermissionNullAlert {
            get {
                return ResourceManager.GetString("UserPermissionNullAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hari Kerja.
        /// </summary>
        public static string WorkDays {
            get {
                return ResourceManager.GetString("WorkDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izin Masuk Kerja.
        /// </summary>
        public static string WorkEntryRequest {
            get {
                return ResourceManager.GetString("WorkEntryRequest", resourceCulture);
            }
        }
    }
}
