//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHR.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DHR.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Me.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowance.
        /// </summary>
        public static string Allowance {
            get {
                return ResourceManager.GetString("Allowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowance Days.
        /// </summary>
        public static string AllowanceDays {
            get {
                return ResourceManager.GetString("AllowanceDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllowanceTotal.
        /// </summary>
        public static string AllowanceTotal {
            get {
                return ResourceManager.GetString("AllowanceTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        public static string AttendanceMenu {
            get {
                return ResourceManager.GetString("AttendanceMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefit.
        /// </summary>
        public static string Benefit {
            get {
                return ResourceManager.GetString("Benefit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Travel.
        /// </summary>
        public static string BusinessTravelRequest {
            get {
                return ResourceManager.GetString("BusinessTravelRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Days.
        /// </summary>
        public static string CalendarDays {
            get {
                return ResourceManager.GetString("CalendarDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your Password.
        /// </summary>
        public static string ChangeyourPassword {
            get {
                return ResourceManager.GetString("ChangeyourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Password.
        /// </summary>
        public static string EditPassword {
            get {
                return ResourceManager.GetString("EditPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Level.
        /// </summary>
        public static string EducationLevel {
            get {
                return ResourceManager.GetString("EducationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inpatient Care.
        /// </summary>
        public static string InpatientCare {
            get {
                return ResourceManager.GetString("InpatientCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late.
        /// </summary>
        public static string Late {
            get {
                return ResourceManager.GetString("Late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        public static string LeaveRequest {
            get {
                return ResourceManager.GetString("LeaveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Taken.
        /// </summary>
        public static string LeaveTaken {
            get {
                return ResourceManager.GetString("LeaveTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maternity Expenses.
        /// </summary>
        public static string MaternityExpenses {
            get {
                return ResourceManager.GetString("MaternityExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Claim.
        /// </summary>
        public static string MedicalClaimMenu {
            get {
                return ResourceManager.GetString("MedicalClaimMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Info.
        /// </summary>
        public static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optical Services.
        /// </summary>
        public static string OpticalServices {
            get {
                return ResourceManager.GetString("OpticalServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out.
        /// </summary>
        public static string Out {
            get {
                return ResourceManager.GetString("Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outpatient Care.
        /// </summary>
        public static string OutpatientCare {
            get {
                return ResourceManager.GetString("OutpatientCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string PermissionRequest {
            get {
                return ResourceManager.GetString("PermissionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string RequestMenu {
            get {
                return ResourceManager.GetString("RequestMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time-Off.
        /// </summary>
        public static string TimeOff {
            get {
                return ResourceManager.GetString("TimeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you believe you have submitted a business trip request but it is not showing here, please contact HR..
        /// </summary>
        public static string UserBusinessTripNullAlert {
            get {
                return ResourceManager.GetString("UserBusinessTripNullAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you believe you have submitted a work entry permission request but it is not showing here, please contact HR..
        /// </summary>
        public static string UserEntryPermissionNullAlert {
            get {
                return ResourceManager.GetString("UserEntryPermissionNullAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you believe you have submitted an inpatient claim but it is not showing here, please contact HR..
        /// </summary>
        public static string UserInpatientNullAlert {
            get {
                return ResourceManager.GetString("UserInpatientNullAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you believe you have submitted a leave request but it is not showing here, please contact HR..
        /// </summary>
        public static string UserLeaveNullAlert {
            get {
                return ResourceManager.GetString("UserLeaveNullAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you believe you have submitted a maternity service claim but it is not showing here, please contact HR..
        /// </summary>
        public static string UserMaternityNullAlert {
            get {
                return ResourceManager.GetString("UserMaternityNullAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you believe you have submitted an optical service claim but it is not showing here, please contact HR..
        /// </summary>
        public static string UserOpticalNullAlert {
            get {
                return ResourceManager.GetString("UserOpticalNullAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you believe you have submitted an outpatient claim but it is not showing here, please contact HR..
        /// </summary>
        public static string UserOutpatientNullAlert {
            get {
                return ResourceManager.GetString("UserOutpatientNullAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you believe you have submitted a permission request but it is not showing here, please contact HR..
        /// </summary>
        public static string UserPermissionNullAlert {
            get {
                return ResourceManager.GetString("UserPermissionNullAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Days.
        /// </summary>
        public static string WorkDays {
            get {
                return ResourceManager.GetString("WorkDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Entry Request.
        /// </summary>
        public static string WorkEntryRequest {
            get {
                return ResourceManager.GetString("WorkEntryRequest", resourceCulture);
            }
        }
    }
}
